// @title           Tally API
// @version         1.0
// @description     Backend for Tally — a group card-spending app with JIT authorization and a double-entry ledger.
// @host            localhost:8080
// @BasePath        /

package main

import (
	"context"
	"log/slog"
	"net/http"
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
	"github.com/tally/backend/internal/auth"
	"github.com/tally/backend/internal/cards"
	"github.com/tally/backend/internal/config"
	"github.com/tally/backend/internal/db"
	_ "github.com/tally/backend/docs" // generated by swag init
	"github.com/tally/backend/internal/groups"
	"github.com/tally/backend/internal/highnote"
	"github.com/tally/backend/internal/middleware"
	plaidpkg "github.com/tally/backend/internal/plaid"
	"github.com/tally/backend/internal/users"
)

func main() {
	// Structured JSON logging — readable by Cloud Logging, Datadog, etc.
	logger := slog.New(slog.NewJSONHandler(os.Stdout, &slog.HandlerOptions{
		Level: slog.LevelInfo,
	}))
	slog.SetDefault(logger)

	cfg := config.Load()
	cfg.Validate()

	if cfg.Environment == "production" {
		gin.SetMode(gin.ReleaseMode)
	}

	// ── Datastore connections ─────────────────────────────────────────────────
	pool, err := db.Connect(cfg.DatabaseURL)
	if err != nil {
		slog.Error("postgres connect failed", "error", err)
		os.Exit(1)
	}
	defer pool.Close()

	rdb, err := db.ConnectRedis(cfg.RedisURL)
	if err != nil {
		slog.Error("redis connect failed", "error", err)
		os.Exit(1)
	}
	defer rdb.Close()

	// ── Schema migrations (idempotent — safe to run on every boot) ────────────
	if err := db.Migrate(cfg.DatabaseURL); err != nil {
		slog.Error("migration failed", "error", err)
		os.Exit(1)
	}

	// ── Clients ───────────────────────────────────────────────────────────────
	// Use the mock Highnote client unless a real API key is configured.
	var hnClient highnote.CardIssuingClient
	if cfg.HighnoteAPIKey != "" {
		hnClient = highnote.NewRealClient(cfg.HighnoteAPIKey)
		slog.Info("highnote real client active")
	} else {
		hnClient = highnote.NewMockClient()
		slog.Info("highnote mock client active")
	}

	var plaidClient plaidpkg.Client
	if cfg.PlaidClientID != "" {
		plaidClient = plaidpkg.NewRealClient(cfg.PlaidClientID, cfg.PlaidSecret, cfg.PlaidEnv)
		slog.Info("plaid real client active", "env", cfg.PlaidEnv)
	} else {
		plaidClient = plaidpkg.NewMockClient()
		slog.Info("plaid mock client active")
	}

	// ── Router ────────────────────────────────────────────────────────────────
	r := gin.New()
	r.Use(gin.Recovery())
	r.Use(middleware.RequestLogger())

	r.GET("/healthz", func(c *gin.Context) {
		c.JSON(http.StatusOK, gin.H{"status": "ok"})
	})
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	v1 := r.Group("/v1")
	{
		// ── Machine-to-machine routes (HMAC, no JWT) ──────────────────────────
		// Middleware order: rate limit → HMAC verification → idempotency.
		// Rate limiting runs first to shed load before we touch Redis or the DB.
		// HMAC verification must run before idempotency so we don't cache
		// responses to unsigned (potentially spoofed) requests.
		authGroup := v1.Group("/auth")
		authGroup.Use(middleware.RateLimit(rdb, 120, time.Minute))
		authGroup.Use(middleware.HMACVerification(cfg.WebhookSecret))
		authGroup.Use(middleware.Idempotency(rdb))
		jit := auth.NewJITHandler(pool, rdb, cfg, plaidClient)
		authGroup.POST("/jit", jit.Authorize)

		cardHandler := cards.NewHandler(pool, rdb, cfg, hnClient, plaidClient)

		hnWebhook := v1.Group("/webhooks/highnote")
		hnWebhook.Use(middleware.RateLimit(rdb, 120, time.Minute))
		hnWebhook.Use(middleware.HMACVerification(cfg.HighnoteWebhookSecret))
		hnWebhook.Use(middleware.Idempotency(rdb))
		hnWebhook.POST("/authorization", cardHandler.HighnoteAuthorize)

		// ── User-facing routes (Clerk JWT required) ───────────────────────────
		api := v1.Group("")
		if cfg.ClerkJWKSURL != "" {
			api.Use(middleware.ClerkAuth(cfg.ClerkJWKSURL))
		} else {
			slog.Warn("CLERK_JWKS_URL not set — using dev auth bypass (set DEV_USER_ID in .env)")
			api.Use(middleware.DevAuth(cfg.DevUserID))
		}

		userHandler := users.NewHandler(pool)
		api.POST("/users/me", userHandler.Me)

		groupHandler := groups.NewHandler(pool)
		api.POST("/groups",     groupHandler.CreateGroup)
		api.GET("/groups",      groupHandler.ListGroups)

		// Routes that require the caller to be a member of the group.
		groupMember := api.Group("/groups/:id")
		groupMember.Use(middleware.RequireGroupMember(pool))
		groupMember.GET("",              groupHandler.GetGroup)
		groupMember.GET("/transactions", groupHandler.ListTransactions)
		groupMember.POST("/members",     groupHandler.AddMember)

		plaidHandler := plaidpkg.NewHandler(pool, plaidClient)
		api.POST("/plaid/link-token",     plaidHandler.CreateLinkToken)
		api.POST("/plaid/exchange-token", plaidHandler.ExchangeToken)
		api.GET("/plaid/accounts",        plaidHandler.ListAccounts)
		api.DELETE("/plaid/accounts",     plaidHandler.UnlinkAccount)

		api.POST("/cards/issue",  cardHandler.IssueCard)
		api.POST("/wallets/load", cardHandler.LoadWallet)
	}

	// ── HTTP server with graceful shutdown ────────────────────────────────────
	srv := &http.Server{
		Addr:         ":" + cfg.Port,
		Handler:      r,
		ReadTimeout:  10 * time.Second,
		WriteTimeout: 10 * time.Second,
		IdleTimeout:  60 * time.Second,
	}

	go func() {
		slog.Info("tally backend starting", "port", cfg.Port, "env", cfg.Environment)
		if err := srv.ListenAndServe(); err != nil && err != http.ErrServerClosed {
			slog.Error("server error", "error", err)
			os.Exit(1)
		}
	}()

	quit := make(chan os.Signal, 1)
	signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)
	<-quit

	slog.Info("shutdown signal received — draining connections")
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()

	if err := srv.Shutdown(ctx); err != nil {
		slog.Error("shutdown error", "error", err)
	}
	slog.Info("tally backend stopped")
}
