// @title           Tally API
// @version         1.0
// @description     Backend for Tally — a group card-spending app with JIT authorization and a double-entry ledger.
// @host            localhost:8080
// @BasePath        /

package main

import (
	"context"
	"log/slog"
	"net/http"
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/google/uuid"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
	"github.com/tally/backend/internal/auth"
	"github.com/tally/backend/internal/cards"
	"github.com/tally/backend/internal/config"
	"github.com/tally/backend/internal/db"
	_ "github.com/tally/backend/docs" // generated by swag init
	"github.com/tally/backend/internal/groups"
	"github.com/tally/backend/internal/middleware"
	"github.com/tally/backend/internal/paysession"
	"github.com/tally/backend/internal/receipts"
	"github.com/tally/backend/internal/settlement"
	"github.com/tally/backend/internal/stripeidentity"
	"github.com/tally/backend/internal/stripeissuing"
	"github.com/tally/backend/internal/stripepayment"
	"github.com/tally/backend/internal/users"
	"github.com/tally/backend/internal/webhooks"
	"github.com/tally/backend/internal/ws"
)

func main() {
	// Structured JSON logging — readable by Cloud Logging, Datadog, etc.
	logger := slog.New(slog.NewJSONHandler(os.Stdout, &slog.HandlerOptions{
		Level: slog.LevelInfo,
	}))
	slog.SetDefault(logger)

	cfg := config.Load()
	cfg.Validate()

	if cfg.Environment == "production" {
		gin.SetMode(gin.ReleaseMode)
	}

	// ── Datastore connections ─────────────────────────────────────────────────
	pool, err := db.Connect(cfg.DatabaseURL)
	if err != nil {
		slog.Error("postgres connect failed", "error", err)
		os.Exit(1)
	}
	defer pool.Close()

	rdb, err := db.ConnectRedis(cfg.RedisURL)
	if err != nil {
		slog.Error("redis connect failed", "error", err)
		os.Exit(1)
	}
	defer rdb.Close()

	// ── Schema migrations (idempotent — safe to run on every boot) ────────────
	if err := db.Migrate(cfg.DatabaseURL); err != nil {
		slog.Error("migration failed", "error", err)
		os.Exit(1)
	}

	// ── Stripe clients ────────────────────────────────────────────────────────
	var issuingClient stripeissuing.CardIssuingClient
	var paymentClient stripepayment.PaymentClient
	var identityClient stripeidentity.IdentityClient

	if cfg.StripeSecretKey != "" {
		issuingClient = stripeissuing.NewRealClient(cfg.StripeSecretKey)
		paymentClient = stripepayment.NewRealClient(cfg.StripeSecretKey)
		identityClient = stripeidentity.NewRealClient(cfg.StripeSecretKey)
		slog.Info("stripe real clients active")
	} else {
		issuingClient = stripeissuing.NewMockClient()
		paymentClient = stripepayment.NewMockClient()
		identityClient = stripeidentity.NewMockClient()
		slog.Info("stripe mock clients active (STRIPE_SECRET_KEY not set)")
	}

	// ── Background settlement worker ──────────────────────────────────────────
	workerCtx, workerCancel := context.WithCancel(context.Background())
	defer workerCancel()
	settlement.StartSettlementWorker(workerCtx, pool, paymentClient)

	// ── Router ────────────────────────────────────────────────────────────────
	r := gin.New()
	r.Use(gin.Recovery())
	r.Use(middleware.RequestLogger())

	r.GET("/healthz", func(c *gin.Context) {
		c.JSON(http.StatusOK, gin.H{"status": "ok"})
	})
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	v1 := r.Group("/v1")
	{
		// ── Machine-to-machine routes (HMAC + idempotency, no JWT) ────────────
		// Rate limit → HMAC verification → idempotency (in that order).
		authGroup := v1.Group("/auth")
		authGroup.Use(middleware.RateLimit(rdb, 120, time.Minute))
		authGroup.Use(middleware.HMACVerification(cfg.WebhookSecret))
		authGroup.Use(middleware.Idempotency(rdb))
		jit := auth.NewJITHandler(pool, rdb, cfg)
		authGroup.POST("/jit", jit.Authorize)

		// ── Stripe webhooks — Stripe's native signature scheme ────────────────
		// These endpoints must NOT use the custom HMAC middleware.
		// stripe.ConstructEvent() is called inside each handler.
		stripeWebhooks := v1.Group("/webhooks/stripe")
		stripeWebhooks.Use(middleware.RateLimit(rdb, 120, time.Minute))
		stripeHandler := webhooks.NewStripeHandler(pool, paymentClient, issuingClient, cfg)

		// Wire the settlement goroutine into the issuing-authorization webhook.
		stripeWebhooks.POST("/issuing-authorization", func(c *gin.Context) {
			stripeHandler.HandleIssuingAuthorization(c)
		})
		stripeWebhooks.POST("/reversal", stripeHandler.HandleReversal)
		stripeWebhooks.POST("/identity",  stripeHandler.HandleIdentity)

		// ── User-facing routes (Clerk JWT required) ───────────────────────────
		api := v1.Group("")
		api.Use(middleware.RateLimit(rdb, 300, time.Minute))
		if cfg.ClerkJWKSURL != "" {
			api.Use(middleware.ClerkAuth(cfg.ClerkJWKSURL))
		} else {
			slog.Warn("CLERK_JWKS_URL not set — using dev auth bypass (set DEV_USER_ID in .env)")
			api.Use(middleware.DevAuth(cfg.DevUserID))
		}

		// ── Users ─────────────────────────────────────────────────────────────
		userHandler := users.NewHandler(pool, paymentClient, identityClient)
		api.POST("/users/me", userHandler.Me)
		api.POST("/users/me/kyc", userHandler.StartKYC)

		// Payment method management
		api.POST("/users/me/payment-method",                 userHandler.CreateSetupIntent)
		api.POST("/users/me/payment-method/confirm",         userHandler.ConfirmPaymentMethod)
		api.POST("/users/me/payment-method/backup",          userHandler.CreateBackupSetupIntent)
		api.POST("/users/me/payment-method/backup/confirm",  userHandler.ConfirmBackupPaymentMethod)

		// ── Groups ────────────────────────────────────────────────────────────
		groupHandler := groups.NewHandler(pool)
		api.POST("/groups", groupHandler.CreateGroup)
		api.GET("/groups",  groupHandler.ListGroups)

		// Routes that require the caller to be a member of the group.
		groupMember := api.Group("/groups/:id")
		groupMember.Use(middleware.RequireGroupMember(pool))
		groupMember.GET("",              groupHandler.GetGroup)
		groupMember.GET("/transactions", groupHandler.ListTransactions)
		groupMember.GET("/transactions/:txnId", groupHandler.GetTransaction)
		groupMember.POST("/members",     groupHandler.AddMember)
		groupMember.GET("/ious",         groupHandler.ListIOUs)
		groupMember.POST("/ious/:iouId/settle", groupHandler.SettleIOU)

		// Leader-only routes — requires caller to be the group leader.
		groupLeader := api.Group("/groups/:id")
		groupLeader.Use(middleware.RequireGroupLeader(pool))
		groupLeader.DELETE("", groupHandler.ArchiveGroup)
		groupLeader.POST("/leader/authorize",   groupHandler.SetLeaderAuthorization)
		groupLeader.DELETE("/leader/authorize", groupHandler.ClearLeaderAuthorization)

		// Leader auth GET is readable by any member.
		groupMember.GET("/leader/authorize", groupHandler.GetLeaderAuthorization)

		// ── Cards ─────────────────────────────────────────────────────────────
		cardHandler := cards.NewHandler(pool, rdb, cfg, issuingClient)
		api.POST("/cards/issue", cardHandler.IssueCard)

		// ── Receipt parsing (stateless, rate-limited) ────────────────────────
		receiptHandler := receipts.NewHandler(cfg.GeminiAPIKey, cfg.GeminiModel)
		receiptGroup := api.Group("/receipts")
		receiptGroup.Use(middleware.RateLimit(rdb, 120, time.Minute))
		receiptGroup.POST("/parse", receiptHandler.ParseReceipt)

		// ── WebSocket for real-time session updates ──────────────────────
		wsManager := ws.NewManager()
		wsHandler := ws.NewWSHandler(wsManager)

		// ── Receipt persistence (per-group, member-scoped) ───────────────
		receiptStore := receipts.NewStoreHandler(pool, wsManager)
		groupMember.POST("/receipts", receiptStore.SaveReceipt)
		groupMember.GET("/receipts/:receiptId", receiptStore.GetReceipt)
		groupMember.PUT("/receipts/:receiptId/items/:itemId/claim", receiptStore.ClaimItem)
		groupMember.DELETE("/receipts/:receiptId/items/:itemId/claim", receiptStore.ReleaseClaim)
		groupMember.GET("/receipts/:receiptId/confirmations", receiptStore.GetConfirmations)
		groupMember.POST("/receipts/:receiptId/confirm", receiptStore.ConfirmSelections)
		groupLeader.POST("/receipts/:receiptId/items/assign", receiptStore.AssignItems)

		// ── Payment sessions ─────────────────────────────────────────────
		payHandler := paysession.NewHandler(pool, wsManager)
		groupMember.POST("/sessions", payHandler.CreateSession)
		groupMember.GET("/sessions/active", payHandler.GetActiveSession)
		groupMember.GET("/sessions/:sessionId", payHandler.GetSession)
		groupMember.PATCH("/sessions/:sessionId", payHandler.UpdateSession)
		groupMember.DELETE("/sessions/:sessionId", payHandler.CancelSession)
		groupMember.POST("/sessions/:sessionId/splits", payHandler.SetSplits)
		groupMember.POST("/sessions/:sessionId/confirm", payHandler.ConfirmSplit)
		groupMember.POST("/sessions/:sessionId/approve", payHandler.ApproveSession)
		groupMember.POST("/sessions/:sessionId/simulate-tap", payHandler.SimulateTap)
		groupMember.GET("/sessions/:sessionId/ws", wsHandler.HandleUpgrade)
	}

	// ── Dev-only: trigger settlement for an APPROVED transaction ───────────────
	// Allows testing settlement without waiting for the 30-second sweep.
	if cfg.Environment != "production" {
		v1.POST("/dev/settle/:txnId", func(c *gin.Context) {
			txnID, err := uuid.Parse(c.Param("txnId"))
			if err != nil {
				c.JSON(http.StatusBadRequest, gin.H{"error": "invalid transaction_id"})
				return
			}
			ctx, cancel := context.WithTimeout(c.Request.Context(), 5*time.Minute)
			defer cancel()
			if err := settlement.SettleApprovedTransaction(ctx, pool, paymentClient, txnID); err != nil {
				slog.Error("dev settle failed", "transaction_id", txnID, "error", err)
				c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
				return
			}
			c.JSON(http.StatusOK, gin.H{"status": "settlement_completed"})
		})
	}

	// ── HTTP server with graceful shutdown ────────────────────────────────────
	srv := &http.Server{
		Addr:         ":" + cfg.Port,
		Handler:      r,
		ReadTimeout:  10 * time.Second,
		WriteTimeout: 10 * time.Second,
		IdleTimeout:  60 * time.Second,
	}

	go func() {
		slog.Info("tally backend starting", "port", cfg.Port, "env", cfg.Environment)
		if err := srv.ListenAndServe(); err != nil && err != http.ErrServerClosed {
			slog.Error("server error", "error", err)
			os.Exit(1)
		}
	}()

	quit := make(chan os.Signal, 1)
	signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)
	<-quit

	slog.Info("shutdown signal received — draining connections")
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()

	if err := srv.Shutdown(ctx); err != nil {
		slog.Error("shutdown error", "error", err)
	}
	slog.Info("tally backend stopped")
}
