// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/auth/jit": {
            "post": {
                "description": "Generic card-processor JIT authorization endpoint. Runs the 5-tier funding waterfall and returns APPROVE or DECLINE. Requires X-Tally-Signature and Idempotency-Key headers.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "JIT card authorization",
                "parameters": [
                    {
                        "type": "string",
                        "description": "HMAC-SHA256 signature: sha256=\u003chex\u003e",
                        "name": "X-Tally-Signature",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Unique key to deduplicate retries",
                        "name": "Idempotency-Key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Authorization request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.JITRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.JITResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/auth.JITResponse"
                        }
                    }
                }
            }
        },
        "/v1/cards/issue": {
            "post": {
                "description": "Creates a Highnote cardholder and virtual card for a member. The returned card_token is used to identify the card in JIT authorization webhooks.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cards"
                ],
                "summary": "Issue a virtual card",
                "parameters": [
                    {
                        "description": "Member identity",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/cards.issueCardRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/cards.issueCardResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/groups": {
            "post": {
                "description": "Creates a new Tally group and provisions its double-entry liability ledger account.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "groups"
                ],
                "summary": "Create a group",
                "parameters": [
                    {
                        "description": "Group details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/groups.createGroupRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/groups.createGroupResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/groups/{id}": {
            "get": {
                "description": "Returns group metadata (name, currency) and a summary of all members including balances.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "groups"
                ],
                "summary": "Get a group",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Group ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/groups.getGroupResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/groups/{id}/members": {
            "post": {
                "description": "Creates a member record (with optional Plaid tokens) and provisions their asset ledger account.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "groups"
                ],
                "summary": "Add a member to a group",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Group ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Member details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/groups.addMemberRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/groups.addMemberResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/groups/{id}/transactions": {
            "get": {
                "description": "Returns the 50 most recent transactions for a group, newest first.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "groups"
                ],
                "summary": "List transactions",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Group ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/groups.transactionSummary"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/wallets/load": {
            "post": {
                "description": "Credits a member's Tally wallet balance (Tier 1 funding source). Also syncs the load to Highnote on a best-effort basis.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cards"
                ],
                "summary": "Load a member's wallet",
                "parameters": [
                    {
                        "description": "Load details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/cards.loadWalletRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/cards.loadWalletResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/webhooks/highnote/authorization": {
            "post": {
                "description": "Receives Highnote card authorization events and runs the 5-tier funding waterfall (Tally balance → primary bank → secondary bank → leader overwrite → partial auth). Requires X-Tally-Signature and Idempotency-Key headers.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "webhooks"
                ],
                "summary": "Highnote JIT authorization webhook",
                "parameters": [
                    {
                        "type": "string",
                        "description": "HMAC-SHA256 signature: sha256=\u003chex\u003e",
                        "name": "X-Tally-Signature",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Unique key to deduplicate retries",
                        "name": "Idempotency-Key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Highnote authorization event",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/cards.hnAuthRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/cards.hnAuthResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "auth.JITRequest": {
            "type": "object",
            "required": [
                "amount_cents",
                "card_token",
                "currency",
                "idempotency_key"
            ],
            "properties": {
                "amount_cents": {
                    "type": "integer"
                },
                "card_token": {
                    "type": "string"
                },
                "currency": {
                    "type": "string"
                },
                "idempotency_key": {
                    "description": "IdempotencyKey must also be sent in the Idempotency-Key header so the\nmiddleware can deduplicate without parsing the body.",
                    "type": "string"
                },
                "merchant_category": {
                    "type": "string"
                },
                "merchant_name": {
                    "type": "string"
                }
            }
        },
        "auth.JITResponse": {
            "type": "object",
            "properties": {
                "approved_amount_cents": {
                    "description": "\u003c requested when partial",
                    "type": "integer"
                },
                "decision": {
                    "description": "\"APPROVE\" | \"DECLINE\"",
                    "type": "string"
                },
                "reason": {
                    "description": "populated on DECLINE",
                    "type": "string"
                },
                "transaction_id": {
                    "description": "populated on APPROVE",
                    "type": "string"
                }
            }
        },
        "cards.hnAmount": {
            "type": "object",
            "properties": {
                "currencyCode": {
                    "type": "string"
                },
                "value": {
                    "type": "integer"
                }
            }
        },
        "cards.hnAuthRequest": {
            "type": "object",
            "properties": {
                "authorizationRequestId": {
                    "type": "string"
                },
                "cardId": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "merchantDetails": {
                    "$ref": "#/definitions/cards.hnMerchant"
                },
                "transactionAmount": {
                    "$ref": "#/definitions/cards.hnAmount"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "cards.hnAuthResponse": {
            "type": "object",
            "properties": {
                "approvedTransactionAmount": {
                    "$ref": "#/definitions/cards.hnAmount"
                },
                "authorizationResponseCode": {
                    "type": "string"
                }
            }
        },
        "cards.hnMerchant": {
            "type": "object",
            "properties": {
                "categoryCode": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "cards.issueCardRequest": {
            "type": "object",
            "required": [
                "email",
                "first_name",
                "last_name",
                "member_id"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "member_id": {
                    "type": "string"
                }
            }
        },
        "cards.issueCardResponse": {
            "type": "object",
            "properties": {
                "card_id": {
                    "type": "string"
                },
                "card_token": {
                    "type": "string"
                },
                "cardholder_id": {
                    "type": "string"
                }
            }
        },
        "cards.loadWalletRequest": {
            "type": "object",
            "required": [
                "amount_cents",
                "member_id"
            ],
            "properties": {
                "amount_cents": {
                    "type": "integer"
                },
                "member_id": {
                    "type": "string"
                }
            }
        },
        "cards.loadWalletResponse": {
            "type": "object",
            "properties": {
                "new_balance_cents": {
                    "type": "integer"
                }
            }
        },
        "groups.addMemberRequest": {
            "type": "object",
            "required": [
                "display_name"
            ],
            "properties": {
                "display_name": {
                    "type": "string"
                },
                "is_leader": {
                    "type": "boolean"
                },
                "plaid_access_token": {
                    "type": "string"
                },
                "plaid_account_id": {
                    "type": "string"
                },
                "split_weight": {
                    "type": "number"
                }
            }
        },
        "groups.addMemberResponse": {
            "type": "object",
            "properties": {
                "display_name": {
                    "type": "string"
                },
                "member_id": {
                    "type": "string"
                },
                "split_weight": {
                    "type": "number"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "groups.createGroupRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "currency": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "groups.createGroupResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "currency": {
                    "type": "string"
                },
                "group_id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "groups.getGroupResponse": {
            "type": "object",
            "properties": {
                "currency": {
                    "type": "string"
                },
                "group_id": {
                    "type": "string"
                },
                "members": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/groups.memberSummary"
                    }
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "groups.memberSummary": {
            "type": "object",
            "properties": {
                "display_name": {
                    "type": "string"
                },
                "has_card": {
                    "type": "boolean"
                },
                "is_leader": {
                    "type": "boolean"
                },
                "member_id": {
                    "type": "string"
                },
                "split_weight": {
                    "type": "number"
                },
                "tally_balance_cents": {
                    "type": "integer"
                }
            }
        },
        "groups.transactionSummary": {
            "type": "object",
            "properties": {
                "amount_cents": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "currency": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "merchant_category": {
                    "type": "string"
                },
                "merchant_name": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Tally API",
	Description:      "Backend for Tally — a group card-spending app with JIT authorization and a double-entry ledger.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
